# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    depends_on:
      - postgres
    container_name: backend
    ports:
      - '3000:3000'
    build: ./backend/justapi
    # restart: always
    env_file:
      - env/.env
  frontend:
    container_name: frontend
    ports:
      - '8000:8000'
    build: ./frontend
    # restart: always
    env_file:
      - env/.env

volumes:
  postgres: